// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class Created extends ethereum.Event {
  get params(): Created__Params {
    return new Created__Params(this);
  }
}

export class Created__Params {
  _event: Created;

  constructor(event: Created) {
    this._event = event;
  }

  get sender(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get owner(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get proxy(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get cache(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class QProxyFactory extends ethereum.SmartContract {
  static bind(address: Address): QProxyFactory {
    return new QProxyFactory("QProxyFactory", address);
  }

  build(): Address {
    let result = super.call("build", "build():(address)", []);

    return result[0].toAddress();
  }

  try_build(): ethereum.CallResult<Address> {
    let result = super.tryCall("build", "build():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  build1(owner: Address): Address {
    let result = super.call("build", "build(address):(address)", [
      ethereum.Value.fromAddress(owner),
    ]);

    return result[0].toAddress();
  }

  try_build1(owner: Address): ethereum.CallResult<Address> {
    let result = super.tryCall("build", "build(address):(address)", [
      ethereum.Value.fromAddress(owner),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  cache(): Address {
    let result = super.call("cache", "cache():(address)", []);

    return result[0].toAddress();
  }

  try_cache(): ethereum.CallResult<Address> {
    let result = super.tryCall("cache", "cache():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  isProxy(param0: Address): boolean {
    let result = super.call("isProxy", "isProxy(address):(bool)", [
      ethereum.Value.fromAddress(param0),
    ]);

    return result[0].toBoolean();
  }

  try_isProxy(param0: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("isProxy", "isProxy(address):(bool)", [
      ethereum.Value.fromAddress(param0),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class BuildCall extends ethereum.Call {
  get inputs(): BuildCall__Inputs {
    return new BuildCall__Inputs(this);
  }

  get outputs(): BuildCall__Outputs {
    return new BuildCall__Outputs(this);
  }
}

export class BuildCall__Inputs {
  _call: BuildCall;

  constructor(call: BuildCall) {
    this._call = call;
  }
}

export class BuildCall__Outputs {
  _call: BuildCall;

  constructor(call: BuildCall) {
    this._call = call;
  }

  get proxy(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class Build1Call extends ethereum.Call {
  get inputs(): Build1Call__Inputs {
    return new Build1Call__Inputs(this);
  }

  get outputs(): Build1Call__Outputs {
    return new Build1Call__Outputs(this);
  }
}

export class Build1Call__Inputs {
  _call: Build1Call;

  constructor(call: Build1Call) {
    this._call = call;
  }

  get owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class Build1Call__Outputs {
  _call: Build1Call;

  constructor(call: Build1Call) {
    this._call = call;
  }

  get proxy(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}
