type Tidalx @entity {
    id: ID!
    color: String!                                      # Bronze, Silver, Gold
    poolCount: Int!                                     # Number of pools
    finalizedPoolCount: Int!                            # Number of finalized pools
    crpCount: Int!                                      # Number of CRP
    pools: [Pool!] @derivedFrom(field: "factoryID")
    txCount: BigInt!                                    # Number of txs
    totalLiquidity: BigDecimal!                         # All the pools liquidity value in USD
    totalSwapVolume: BigDecimal!                        # All the swap volume in USD
    totalSwapFee: BigDecimal!                           # All the swap fee in USD
}

type Pool @entity {
    id: ID!                                             # Pool address
    controller: Bytes!                                  # Controller address
    publicSwap: Boolean!                                # isPublicSwap
    finalized: Boolean!                                 # isFinalized
    crp: Boolean!                                       # Is configurable rights pool
    crpController: Bytes                                # CRP controller address
    symbol: String                                      # Pool token symbol
    name: String                                        # Pool token name
    rights: [String!]!                                  # List of rights (for CRP)
    # CRP / ETF config
    cap: BigInt                                         # Maximum supply if any (for CRP)
    active: Boolean!                                    # isActive
    managerFee: BigInt!                                 # managerFee Fees
    swapFee: BigDecimal!
    totalWeight: BigDecimal!
    totalShares: BigDecimal!                            # Total pool token shares
    totalSwapVolume: BigDecimal!                        # Total swap volume in USD
    totalSwapFee: BigDecimal!                           # Total swap fee in USD
    liquidity: BigDecimal!                              # Pool liquidity value in USD
    lpVolume24h: BigDecimal!                            # LP token volume in last 24h (USD)
    lpFee24h: BigDecimal!                               # LP fee income in last 24h (USD, effective window)
    lpApr: BigDecimal!                                  # Annualized LP APR (%), fee-based
    lpAprWindow: Int!                                   # Window used: 24/7/30 (days)
    lpLastRefreshBlock: BigInt!                         # Last block where LP metrics were refreshed
    lpBootstrapPrice: BigDecimal!                       # First observed LP price used as fallback reference
    lpBootstrapPoolValue: BigDecimal!                   # First observed pool value used as fallback reference
    lpBootstrapTimestamp: Int!                          # First observed timestamp used as fallback reference
    tokensList: [Bytes!]!                               # Temp workaround until graph supports filtering on derived field
    tokensOriginalList: [Bytes!]!
    tokens: [PoolToken!] @derivedFrom(field: "poolId")
    shares: [PoolShare!] @derivedFrom(field: "poolId")
    createTime: Int!                                    # Block time pool was created
    tokensCount: BigInt!                                # Number of tokens in the pool
    holdersCount: BigInt!                               # Number of addresses holding a positive balance of BPT
    joinsCount: BigInt!                                 # liquidity has been added
    exitsCount: BigInt!                                 # liquidity has been removed
    swapsCount: BigInt!
    factoryID: Tidalx!
    tx: Bytes                                           # Pool creation transaction id
    swaps: [Swap!] @derivedFrom(field: "poolAddress")
    lpKlinesDay: [PoolLpKlineDay!] @derivedFrom(field: "poolId")
    # etfStatus: [EtfStatus!]                             # etf create cycle
    # etype: String                                       # etf open fund types [opened, closed]
}

# type EtfStatus @entity {
#     id: ID!
#     collectPeriod: Int!
#     collectEndTime: Int!
#     closurePeriod: Int!
#     closureEndTime: Int!
# }

type PoolToken @entity {
    id: ID!                                             # poolId + token address
    poolId: Pool!
    symbol: String
    name: String
    decimals: Int!
    address: String!
    balance: BigDecimal!
    denormWeight: BigDecimal!
}

type PoolShare @entity {
    id: ID!                                             # poolId + userAddress
    userAddress: User!
    poolId: Pool!
    balance: BigDecimal!
    userBalance: BigDecimal!
}

type PoolCrpRef @entity {
    id: ID!                                             # pool address
    crp: Bytes!                                         # CRP contract address
}

type PoolLpVolumeHour @entity {
    id: ID!                                             # poolId-hourIndex
    poolId: Pool!
    hourStart: Int!
    volumeUsd: BigDecimal!
}

type PoolLpPriceHour @entity {
    id: ID!                                             # poolId-hourIndex
    poolId: Pool!
    hourStart: Int!
    lpPriceUsd: BigDecimal!
}

type PoolValueHour @entity {
    id: ID!                                             # poolId-hourIndex
    poolId: Pool!
    hourStart: Int!
    poolValueUsd: BigDecimal!
}

type PoolLpKlineDay @entity {
    id: ID!                                             # poolId-dayIndex
    poolId: Pool!
    dayStart: Int!
    poolValueUsd: BigDecimal!                           # Pool total value in USD at this hour
}

type User @entity {
    id: ID!
    sharesOwned: [PoolShare!]  @derivedFrom(field: "userAddress")
    txs: [Transaction!]  @derivedFrom(field: "userAddress")
    swaps: [Swap!]  @derivedFrom(field: "userAddress")
}

type Swap @entity {
    id: ID!                                 #
    caller: Bytes!                          #
    tokenIn: Bytes!                         #
    tokenInSym: String!                     #
    tokenOut: Bytes!                        #
    tokenOutSym: String!                    #
    tokenAmountIn: BigDecimal!              #
    tokenAmountOut: BigDecimal!             #
    poolAddress: Pool
    userAddress: User                       # User address that initiates the swap
    value: BigDecimal!                      # Swap value in USD
    feeValue: BigDecimal!                   # Swap fee value in USD
    poolTotalSwapVolume: BigDecimal!        # Total pool swap volume in USD
    poolTotalSwapFee: BigDecimal!           # Total pool swap fee in USD
    poolLiquidity: BigDecimal!              # Pool liquidity value in USD
    timestamp: Int!
}

type Transaction @entity {
    id: ID!                         # Log ID
    tx: Bytes!
    event: String
    block: Int!
    timestamp: Int!
    gasUsed: BigDecimal!
    gasPrice: BigDecimal!
    poolAddress: Pool
    userAddress: User
    action: SwapType
    sender: Bytes
    tokenAddress: String
    tokenAmountInOut: BigDecimal
    newAmount: BigDecimal
    lpTokenShare: BigDecimal
}

type TokenPrice @entity {
    id: ID!
    symbol: String
    name: String
    decimals: Int!
    price: BigDecimal!
    poolLiquidity: BigDecimal!
    poolTokenId: String
}

enum SwapType {
    swapExactAmountIn,
    swapExactAmountOut,
    joinswapExternAmountIn,
    joinswapPoolAmountOut,
    exitswapPoolAmountIn,
    exitswapExternAmountOut
}
