// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class Approval extends ethereum.Event {
  get params(): Approval__Params {
    return new Approval__Params(this);
  }
}

export class Approval__Params {
  _event: Approval;

  constructor(event: Approval) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get spender(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class CapChanged extends ethereum.Event {
  get params(): CapChanged__Params {
    return new CapChanged__Params(this);
  }
}

export class CapChanged__Params {
  _event: CapChanged;

  constructor(event: CapChanged) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get oldCap(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get newCap(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class ExitPoolSwitchChanged extends ethereum.Event {
  get params(): ExitPoolSwitchChanged__Params {
    return new ExitPoolSwitchChanged__Params(this);
  }
}

export class ExitPoolSwitchChanged__Params {
  _event: ExitPoolSwitchChanged;

  constructor(event: ExitPoolSwitchChanged) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get enabled(): boolean {
    return this._event.parameters[1].value.toBoolean();
  }
}

export class ExitPoolWithSigSwitchChanged extends ethereum.Event {
  get params(): ExitPoolWithSigSwitchChanged__Params {
    return new ExitPoolWithSigSwitchChanged__Params(this);
  }
}

export class ExitPoolWithSigSwitchChanged__Params {
  _event: ExitPoolWithSigSwitchChanged;

  constructor(event: ExitPoolWithSigSwitchChanged) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get enabled(): boolean {
    return this._event.parameters[1].value.toBoolean();
  }
}

export class LogCall extends ethereum.Event {
  get params(): LogCall__Params {
    return new LogCall__Params(this);
  }
}

export class LogCall__Params {
  _event: LogCall;

  constructor(event: LogCall) {
    this._event = event;
  }

  get sig(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get caller(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get data(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class LogExit extends ethereum.Event {
  get params(): LogExit__Params {
    return new LogExit__Params(this);
  }
}

export class LogExit__Params {
  _event: LogExit;

  constructor(event: LogExit) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get tokenOut(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get tokenAmountOut(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class LogJoin extends ethereum.Event {
  get params(): LogJoin__Params {
    return new LogJoin__Params(this);
  }
}

export class LogJoin__Params {
  _event: LogJoin;

  constructor(event: LogJoin) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get tokenIn(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get tokenAmountIn(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class ManageFeeChanged extends ethereum.Event {
  get params(): ManageFeeChanged__Params {
    return new ManageFeeChanged__Params(this);
  }
}

export class ManageFeeChanged__Params {
  _event: ManageFeeChanged;

  constructor(event: ManageFeeChanged) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get oldManageFee(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get newManageFee(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class NewTokenCommitted extends ethereum.Event {
  get params(): NewTokenCommitted__Params {
    return new NewTokenCommitted__Params(this);
  }
}

export class NewTokenCommitted__Params {
  _event: NewTokenCommitted;

  constructor(event: NewTokenCommitted) {
    this._event = event;
  }

  get token(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get caller(): Address {
    return this._event.parameters[2].value.toAddress();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Transfer extends ethereum.Event {
  get params(): Transfer__Params {
    return new Transfer__Params(this);
  }
}

export class Transfer__Params {
  _event: Transfer;

  constructor(event: Transfer) {
    this._event = event;
  }

  get from(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get to(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class ConfigurableRightsPool__gradualUpdateResult {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getStartBlock(): BigInt {
    return this.value0;
  }

  getEndBlock(): BigInt {
    return this.value1;
  }
}

export class ConfigurableRightsPool__newTokenResult {
  value0: Address;
  value1: boolean;
  value2: BigInt;
  value3: BigInt;
  value4: BigInt;

  constructor(
    value0: Address,
    value1: boolean,
    value2: BigInt,
    value3: BigInt,
    value4: BigInt,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddress(this.value0));
    map.set("value1", ethereum.Value.fromBoolean(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    return map;
  }

  getAddr(): Address {
    return this.value0;
  }

  getIsCommitted(): boolean {
    return this.value1;
  }

  getCommitBlock(): BigInt {
    return this.value2;
  }

  getDenorm(): BigInt {
    return this.value3;
  }

  getBalance(): BigInt {
    return this.value4;
  }
}

export class ConfigurableRightsPool__rightsResult {
  value0: boolean;
  value1: boolean;
  value2: boolean;
  value3: boolean;

  constructor(
    value0: boolean,
    value1: boolean,
    value2: boolean,
    value3: boolean,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromBoolean(this.value0));
    map.set("value1", ethereum.Value.fromBoolean(this.value1));
    map.set("value2", ethereum.Value.fromBoolean(this.value2));
    map.set("value3", ethereum.Value.fromBoolean(this.value3));
    return map;
  }

  getCanChangeManageFee(): boolean {
    return this.value0;
  }

  getCanChangeWeights(): boolean {
    return this.value1;
  }

  getCanWhitelistLPs(): boolean {
    return this.value2;
  }

  getCanChangeCap(): boolean {
    return this.value3;
  }
}

export class ConfigurableRightsPool extends ethereum.SmartContract {
  static bind(address: Address): ConfigurableRightsPool {
    return new ConfigurableRightsPool("ConfigurableRightsPool", address);
  }

  DECIMALS(): i32 {
    let result = super.call("DECIMALS", "DECIMALS():(uint8)", []);

    return result[0].toI32();
  }

  try_DECIMALS(): ethereum.CallResult<i32> {
    let result = super.tryCall("DECIMALS", "DECIMALS():(uint8)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  DOMAIN_SEPARATOR(): Bytes {
    let result = super.call(
      "DOMAIN_SEPARATOR",
      "DOMAIN_SEPARATOR():(bytes32)",
      [],
    );

    return result[0].toBytes();
  }

  try_DOMAIN_SEPARATOR(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "DOMAIN_SEPARATOR",
      "DOMAIN_SEPARATOR():(bytes32)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  NAME(): string {
    let result = super.call("NAME", "NAME():(string)", []);

    return result[0].toString();
  }

  try_NAME(): ethereum.CallResult<string> {
    let result = super.tryCall("NAME", "NAME():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  allowance(owner: Address, spender: Address): BigInt {
    let result = super.call(
      "allowance",
      "allowance(address,address):(uint256)",
      [ethereum.Value.fromAddress(owner), ethereum.Value.fromAddress(spender)],
    );

    return result[0].toBigInt();
  }

  try_allowance(owner: Address, spender: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "allowance",
      "allowance(address,address):(uint256)",
      [ethereum.Value.fromAddress(owner), ethereum.Value.fromAddress(spender)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  approve(spender: Address, amount: BigInt): boolean {
    let result = super.call("approve", "approve(address,uint256):(bool)", [
      ethereum.Value.fromAddress(spender),
      ethereum.Value.fromUnsignedBigInt(amount),
    ]);

    return result[0].toBoolean();
  }

  try_approve(spender: Address, amount: BigInt): ethereum.CallResult<boolean> {
    let result = super.tryCall("approve", "approve(address,uint256):(bool)", [
      ethereum.Value.fromAddress(spender),
      ethereum.Value.fromUnsignedBigInt(amount),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  bFactory(): Address {
    let result = super.call("bFactory", "bFactory():(address)", []);

    return result[0].toAddress();
  }

  try_bFactory(): ethereum.CallResult<Address> {
    let result = super.tryCall("bFactory", "bFactory():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  bPool(): Address {
    let result = super.call("bPool", "bPool():(address)", []);

    return result[0].toAddress();
  }

  try_bPool(): ethereum.CallResult<Address> {
    let result = super.tryCall("bPool", "bPool():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  balanceOf(account: Address): BigInt {
    let result = super.call("balanceOf", "balanceOf(address):(uint256)", [
      ethereum.Value.fromAddress(account),
    ]);

    return result[0].toBigInt();
  }

  try_balanceOf(account: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("balanceOf", "balanceOf(address):(uint256)", [
      ethereum.Value.fromAddress(account),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  bspCap(): BigInt {
    let result = super.call("bspCap", "bspCap():(uint256)", []);

    return result[0].toBigInt();
  }

  try_bspCap(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("bspCap", "bspCap():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  canProvideLiquidity(provider: Address): boolean {
    let result = super.call(
      "canProvideLiquidity",
      "canProvideLiquidity(address):(bool)",
      [ethereum.Value.fromAddress(provider)],
    );

    return result[0].toBoolean();
  }

  try_canProvideLiquidity(provider: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "canProvideLiquidity",
      "canProvideLiquidity(address):(bool)",
      [ethereum.Value.fromAddress(provider)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  crpFactory(): Address {
    let result = super.call("crpFactory", "crpFactory():(address)", []);

    return result[0].toAddress();
  }

  try_crpFactory(): ethereum.CallResult<Address> {
    let result = super.tryCall("crpFactory", "crpFactory():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  decimals(): i32 {
    let result = super.call("decimals", "decimals():(uint8)", []);

    return result[0].toI32();
  }

  try_decimals(): ethereum.CallResult<i32> {
    let result = super.tryCall("decimals", "decimals():(uint8)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  decreaseApproval(spender: Address, amount: BigInt): boolean {
    let result = super.call(
      "decreaseApproval",
      "decreaseApproval(address,uint256):(bool)",
      [
        ethereum.Value.fromAddress(spender),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );

    return result[0].toBoolean();
  }

  try_decreaseApproval(
    spender: Address,
    amount: BigInt,
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "decreaseApproval",
      "decreaseApproval(address,uint256):(bool)",
      [
        ethereum.Value.fromAddress(spender),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  exitNonces(param0: Address): BigInt {
    let result = super.call("exitNonces", "exitNonces(address):(uint256)", [
      ethereum.Value.fromAddress(param0),
    ]);

    return result[0].toBigInt();
  }

  try_exitNonces(param0: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("exitNonces", "exitNonces(address):(uint256)", [
      ethereum.Value.fromAddress(param0),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  exitPoolEnabled(): boolean {
    let result = super.call("exitPoolEnabled", "exitPoolEnabled():(bool)", []);

    return result[0].toBoolean();
  }

  try_exitPoolEnabled(): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "exitPoolEnabled",
      "exitPoolEnabled():(bool)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  exitPoolWithSigEnabled(): boolean {
    let result = super.call(
      "exitPoolWithSigEnabled",
      "exitPoolWithSigEnabled():(bool)",
      [],
    );

    return result[0].toBoolean();
  }

  try_exitPoolWithSigEnabled(): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "exitPoolWithSigEnabled",
      "exitPoolWithSigEnabled():(bool)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  exitSigner(): Address {
    let result = super.call("exitSigner", "exitSigner():(address)", []);

    return result[0].toAddress();
  }

  try_exitSigner(): ethereum.CallResult<Address> {
    let result = super.tryCall("exitSigner", "exitSigner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getController(): Address {
    let result = super.call("getController", "getController():(address)", []);

    return result[0].toAddress();
  }

  try_getController(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getController",
      "getController():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getDenormalizedWeight(token: Address): BigInt {
    let result = super.call(
      "getDenormalizedWeight",
      "getDenormalizedWeight(address):(uint256)",
      [ethereum.Value.fromAddress(token)],
    );

    return result[0].toBigInt();
  }

  try_getDenormalizedWeight(token: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getDenormalizedWeight",
      "getDenormalizedWeight(address):(uint256)",
      [ethereum.Value.fromAddress(token)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getQuanSafeMathVersion(): Address {
    let result = super.call(
      "getQuanSafeMathVersion",
      "getQuanSafeMathVersion():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_getQuanSafeMathVersion(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getQuanSafeMathVersion",
      "getQuanSafeMathVersion():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getRightsManagerVersion(): Address {
    let result = super.call(
      "getRightsManagerVersion",
      "getRightsManagerVersion():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_getRightsManagerVersion(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getRightsManagerVersion",
      "getRightsManagerVersion():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getSmartPoolManagerVersion(): Address {
    let result = super.call(
      "getSmartPoolManagerVersion",
      "getSmartPoolManagerVersion():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_getSmartPoolManagerVersion(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getSmartPoolManagerVersion",
      "getSmartPoolManagerVersion():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getWhiteList(): Array<Address> {
    let result = super.call("getWhiteList", "getWhiteList():(address[])", []);

    return result[0].toAddressArray();
  }

  try_getWhiteList(): ethereum.CallResult<Array<Address>> {
    let result = super.tryCall(
      "getWhiteList",
      "getWhiteList():(address[])",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddressArray());
  }

  gradualUpdate(): ConfigurableRightsPool__gradualUpdateResult {
    let result = super.call(
      "gradualUpdate",
      "gradualUpdate():(uint256,uint256)",
      [],
    );

    return new ConfigurableRightsPool__gradualUpdateResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_gradualUpdate(): ethereum.CallResult<ConfigurableRightsPool__gradualUpdateResult> {
    let result = super.tryCall(
      "gradualUpdate",
      "gradualUpdate():(uint256,uint256)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new ConfigurableRightsPool__gradualUpdateResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  hasPermission(permission: i32): boolean {
    let result = super.call("hasPermission", "hasPermission(uint8):(bool)", [
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(permission)),
    ]);

    return result[0].toBoolean();
  }

  try_hasPermission(permission: i32): ethereum.CallResult<boolean> {
    let result = super.tryCall("hasPermission", "hasPermission(uint8):(bool)", [
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(permission)),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  increaseApproval(spender: Address, amount: BigInt): boolean {
    let result = super.call(
      "increaseApproval",
      "increaseApproval(address,uint256):(bool)",
      [
        ethereum.Value.fromAddress(spender),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );

    return result[0].toBoolean();
  }

  try_increaseApproval(
    spender: Address,
    amount: BigInt,
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "increaseApproval",
      "increaseApproval(address,uint256):(bool)",
      [
        ethereum.Value.fromAddress(spender),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  manageFee(): BigInt {
    let result = super.call("manageFee", "manageFee():(uint256)", []);

    return result[0].toBigInt();
  }

  try_manageFee(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("manageFee", "manageFee():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  name(): string {
    let result = super.call("name", "name():(string)", []);

    return result[0].toString();
  }

  try_name(): ethereum.CallResult<string> {
    let result = super.tryCall("name", "name():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  newToken(): ConfigurableRightsPool__newTokenResult {
    let result = super.call(
      "newToken",
      "newToken():(address,bool,uint256,uint256,uint256)",
      [],
    );

    return new ConfigurableRightsPool__newTokenResult(
      result[0].toAddress(),
      result[1].toBoolean(),
      result[2].toBigInt(),
      result[3].toBigInt(),
      result[4].toBigInt(),
    );
  }

  try_newToken(): ethereum.CallResult<ConfigurableRightsPool__newTokenResult> {
    let result = super.tryCall(
      "newToken",
      "newToken():(address,bool,uint256,uint256,uint256)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new ConfigurableRightsPool__newTokenResult(
        value[0].toAddress(),
        value[1].toBoolean(),
        value[2].toBigInt(),
        value[3].toBigInt(),
        value[4].toBigInt(),
      ),
    );
  }

  rights(): ConfigurableRightsPool__rightsResult {
    let result = super.call("rights", "rights():(bool,bool,bool,bool)", []);

    return new ConfigurableRightsPool__rightsResult(
      result[0].toBoolean(),
      result[1].toBoolean(),
      result[2].toBoolean(),
      result[3].toBoolean(),
    );
  }

  try_rights(): ethereum.CallResult<ConfigurableRightsPool__rightsResult> {
    let result = super.tryCall("rights", "rights():(bool,bool,bool,bool)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new ConfigurableRightsPool__rightsResult(
        value[0].toBoolean(),
        value[1].toBoolean(),
        value[2].toBoolean(),
        value[3].toBoolean(),
      ),
    );
  }

  symbol(): string {
    let result = super.call("symbol", "symbol():(string)", []);

    return result[0].toString();
  }

  try_symbol(): ethereum.CallResult<string> {
    let result = super.tryCall("symbol", "symbol():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  totalSupply(): BigInt {
    let result = super.call("totalSupply", "totalSupply():(uint256)", []);

    return result[0].toBigInt();
  }

  try_totalSupply(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("totalSupply", "totalSupply():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  transfer(recipient: Address, amount: BigInt): boolean {
    let result = super.call("transfer", "transfer(address,uint256):(bool)", [
      ethereum.Value.fromAddress(recipient),
      ethereum.Value.fromUnsignedBigInt(amount),
    ]);

    return result[0].toBoolean();
  }

  try_transfer(
    recipient: Address,
    amount: BigInt,
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall("transfer", "transfer(address,uint256):(bool)", [
      ethereum.Value.fromAddress(recipient),
      ethereum.Value.fromUnsignedBigInt(amount),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  transferFrom(sender: Address, recipient: Address, amount: BigInt): boolean {
    let result = super.call(
      "transferFrom",
      "transferFrom(address,address,uint256):(bool)",
      [
        ethereum.Value.fromAddress(sender),
        ethereum.Value.fromAddress(recipient),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );

    return result[0].toBoolean();
  }

  try_transferFrom(
    sender: Address,
    recipient: Address,
    amount: BigInt,
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "transferFrom",
      "transferFrom(address,address,uint256):(bool)",
      [
        ethereum.Value.fromAddress(sender),
        ethereum.Value.fromAddress(recipient),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  vaultAddress(): Address {
    let result = super.call("vaultAddress", "vaultAddress():(address)", []);

    return result[0].toAddress();
  }

  try_vaultAddress(): ethereum.CallResult<Address> {
    let result = super.tryCall("vaultAddress", "vaultAddress():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get factoryAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get poolParams(): ConstructorCallPoolParamsStruct {
    return changetype<ConstructorCallPoolParamsStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get rightsStruct(): ConstructorCallRightsStructStruct {
    return changetype<ConstructorCallRightsStructStruct>(
      this._call.inputValues[2].value.toTuple(),
    );
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ConstructorCallPoolParamsStruct extends ethereum.Tuple {
  get poolTokenSymbol(): string {
    return this[0].toString();
  }

  get poolTokenName(): string {
    return this[1].toString();
  }

  get constituentTokens(): Array<Address> {
    return this[2].toAddressArray();
  }

  get tokenBalances(): Array<BigInt> {
    return this[3].toBigIntArray();
  }

  get tokenWeights(): Array<BigInt> {
    return this[4].toBigIntArray();
  }

  get manageFee(): BigInt {
    return this[5].toBigInt();
  }
}

export class ConstructorCallRightsStructStruct extends ethereum.Tuple {
  get canChangeManageFee(): boolean {
    return this[0].toBoolean();
  }

  get canChangeWeights(): boolean {
    return this[1].toBoolean();
  }

  get canWhitelistLPs(): boolean {
    return this[2].toBoolean();
  }

  get canChangeCap(): boolean {
    return this[3].toBoolean();
  }
}

export class ApproveCall extends ethereum.Call {
  get inputs(): ApproveCall__Inputs {
    return new ApproveCall__Inputs(this);
  }

  get outputs(): ApproveCall__Outputs {
    return new ApproveCall__Outputs(this);
  }
}

export class ApproveCall__Inputs {
  _call: ApproveCall;

  constructor(call: ApproveCall) {
    this._call = call;
  }

  get spender(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class ApproveCall__Outputs {
  _call: ApproveCall;

  constructor(call: ApproveCall) {
    this._call = call;
  }

  get value0(): boolean {
    return this._call.outputValues[0].value.toBoolean();
  }
}

export class BurnPoolShareFromLibCall extends ethereum.Call {
  get inputs(): BurnPoolShareFromLibCall__Inputs {
    return new BurnPoolShareFromLibCall__Inputs(this);
  }

  get outputs(): BurnPoolShareFromLibCall__Outputs {
    return new BurnPoolShareFromLibCall__Outputs(this);
  }
}

export class BurnPoolShareFromLibCall__Inputs {
  _call: BurnPoolShareFromLibCall;

  constructor(call: BurnPoolShareFromLibCall) {
    this._call = call;
  }

  get amount(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class BurnPoolShareFromLibCall__Outputs {
  _call: BurnPoolShareFromLibCall;

  constructor(call: BurnPoolShareFromLibCall) {
    this._call = call;
  }
}

export class CreatePoolCall extends ethereum.Call {
  get inputs(): CreatePoolCall__Inputs {
    return new CreatePoolCall__Inputs(this);
  }

  get outputs(): CreatePoolCall__Outputs {
    return new CreatePoolCall__Outputs(this);
  }
}

export class CreatePoolCall__Inputs {
  _call: CreatePoolCall;

  constructor(call: CreatePoolCall) {
    this._call = call;
  }

  get initialSupply(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get initCap(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class CreatePoolCall__Outputs {
  _call: CreatePoolCall;

  constructor(call: CreatePoolCall) {
    this._call = call;
  }
}

export class DecreaseApprovalCall extends ethereum.Call {
  get inputs(): DecreaseApprovalCall__Inputs {
    return new DecreaseApprovalCall__Inputs(this);
  }

  get outputs(): DecreaseApprovalCall__Outputs {
    return new DecreaseApprovalCall__Outputs(this);
  }
}

export class DecreaseApprovalCall__Inputs {
  _call: DecreaseApprovalCall;

  constructor(call: DecreaseApprovalCall) {
    this._call = call;
  }

  get spender(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class DecreaseApprovalCall__Outputs {
  _call: DecreaseApprovalCall;

  constructor(call: DecreaseApprovalCall) {
    this._call = call;
  }

  get value0(): boolean {
    return this._call.outputValues[0].value.toBoolean();
  }
}

export class ExitPoolCall extends ethereum.Call {
  get inputs(): ExitPoolCall__Inputs {
    return new ExitPoolCall__Inputs(this);
  }

  get outputs(): ExitPoolCall__Outputs {
    return new ExitPoolCall__Outputs(this);
  }
}

export class ExitPoolCall__Inputs {
  _call: ExitPoolCall;

  constructor(call: ExitPoolCall) {
    this._call = call;
  }

  get poolAmountIn(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get slippage(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class ExitPoolCall__Outputs {
  _call: ExitPoolCall;

  constructor(call: ExitPoolCall) {
    this._call = call;
  }
}

export class ExitPoolWithSigCall extends ethereum.Call {
  get inputs(): ExitPoolWithSigCall__Inputs {
    return new ExitPoolWithSigCall__Inputs(this);
  }

  get outputs(): ExitPoolWithSigCall__Outputs {
    return new ExitPoolWithSigCall__Outputs(this);
  }
}

export class ExitPoolWithSigCall__Inputs {
  _call: ExitPoolWithSigCall;

  constructor(call: ExitPoolWithSigCall) {
    this._call = call;
  }

  get poolAmountIn(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get slippage(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get validAfter(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get v(): i32 {
    return this._call.inputValues[3].value.toI32();
  }

  get r(): Bytes {
    return this._call.inputValues[4].value.toBytes();
  }

  get s(): Bytes {
    return this._call.inputValues[5].value.toBytes();
  }
}

export class ExitPoolWithSigCall__Outputs {
  _call: ExitPoolWithSigCall;

  constructor(call: ExitPoolWithSigCall) {
    this._call = call;
  }
}

export class IncreaseApprovalCall extends ethereum.Call {
  get inputs(): IncreaseApprovalCall__Inputs {
    return new IncreaseApprovalCall__Inputs(this);
  }

  get outputs(): IncreaseApprovalCall__Outputs {
    return new IncreaseApprovalCall__Outputs(this);
  }
}

export class IncreaseApprovalCall__Inputs {
  _call: IncreaseApprovalCall;

  constructor(call: IncreaseApprovalCall) {
    this._call = call;
  }

  get spender(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class IncreaseApprovalCall__Outputs {
  _call: IncreaseApprovalCall;

  constructor(call: IncreaseApprovalCall) {
    this._call = call;
  }

  get value0(): boolean {
    return this._call.outputValues[0].value.toBoolean();
  }
}

export class JoinPoolCall extends ethereum.Call {
  get inputs(): JoinPoolCall__Inputs {
    return new JoinPoolCall__Inputs(this);
  }

  get outputs(): JoinPoolCall__Outputs {
    return new JoinPoolCall__Outputs(this);
  }
}

export class JoinPoolCall__Inputs {
  _call: JoinPoolCall;

  constructor(call: JoinPoolCall) {
    this._call = call;
  }

  get poolAmountOut(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class JoinPoolCall__Outputs {
  _call: JoinPoolCall;

  constructor(call: JoinPoolCall) {
    this._call = call;
  }
}

export class MintPoolShareFromLibCall extends ethereum.Call {
  get inputs(): MintPoolShareFromLibCall__Inputs {
    return new MintPoolShareFromLibCall__Inputs(this);
  }

  get outputs(): MintPoolShareFromLibCall__Outputs {
    return new MintPoolShareFromLibCall__Outputs(this);
  }
}

export class MintPoolShareFromLibCall__Inputs {
  _call: MintPoolShareFromLibCall;

  constructor(call: MintPoolShareFromLibCall) {
    this._call = call;
  }

  get amount(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class MintPoolShareFromLibCall__Outputs {
  _call: MintPoolShareFromLibCall;

  constructor(call: MintPoolShareFromLibCall) {
    this._call = call;
  }
}

export class PullPoolShareFromLibCall extends ethereum.Call {
  get inputs(): PullPoolShareFromLibCall__Inputs {
    return new PullPoolShareFromLibCall__Inputs(this);
  }

  get outputs(): PullPoolShareFromLibCall__Outputs {
    return new PullPoolShareFromLibCall__Outputs(this);
  }
}

export class PullPoolShareFromLibCall__Inputs {
  _call: PullPoolShareFromLibCall;

  constructor(call: PullPoolShareFromLibCall) {
    this._call = call;
  }

  get from(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class PullPoolShareFromLibCall__Outputs {
  _call: PullPoolShareFromLibCall;

  constructor(call: PullPoolShareFromLibCall) {
    this._call = call;
  }
}

export class PushPoolShareFromLibCall extends ethereum.Call {
  get inputs(): PushPoolShareFromLibCall__Inputs {
    return new PushPoolShareFromLibCall__Inputs(this);
  }

  get outputs(): PushPoolShareFromLibCall__Outputs {
    return new PushPoolShareFromLibCall__Outputs(this);
  }
}

export class PushPoolShareFromLibCall__Inputs {
  _call: PushPoolShareFromLibCall;

  constructor(call: PushPoolShareFromLibCall) {
    this._call = call;
  }

  get to(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class PushPoolShareFromLibCall__Outputs {
  _call: PushPoolShareFromLibCall;

  constructor(call: PushPoolShareFromLibCall) {
    this._call = call;
  }
}

export class RebalanceCall extends ethereum.Call {
  get inputs(): RebalanceCall__Inputs {
    return new RebalanceCall__Inputs(this);
  }

  get outputs(): RebalanceCall__Outputs {
    return new RebalanceCall__Outputs(this);
  }
}

export class RebalanceCall__Inputs {
  _call: RebalanceCall;

  constructor(call: RebalanceCall) {
    this._call = call;
  }

  get tokenA(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get tokenB(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get deltaWeight(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get slippage(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }
}

export class RebalanceCall__Outputs {
  _call: RebalanceCall;

  constructor(call: RebalanceCall) {
    this._call = call;
  }
}

export class RemoveWhitelistedLiquidityProviderCall extends ethereum.Call {
  get inputs(): RemoveWhitelistedLiquidityProviderCall__Inputs {
    return new RemoveWhitelistedLiquidityProviderCall__Inputs(this);
  }

  get outputs(): RemoveWhitelistedLiquidityProviderCall__Outputs {
    return new RemoveWhitelistedLiquidityProviderCall__Outputs(this);
  }
}

export class RemoveWhitelistedLiquidityProviderCall__Inputs {
  _call: RemoveWhitelistedLiquidityProviderCall;

  constructor(call: RemoveWhitelistedLiquidityProviderCall) {
    this._call = call;
  }

  get provider(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class RemoveWhitelistedLiquidityProviderCall__Outputs {
  _call: RemoveWhitelistedLiquidityProviderCall;

  constructor(call: RemoveWhitelistedLiquidityProviderCall) {
    this._call = call;
  }
}

export class SetCapCall extends ethereum.Call {
  get inputs(): SetCapCall__Inputs {
    return new SetCapCall__Inputs(this);
  }

  get outputs(): SetCapCall__Outputs {
    return new SetCapCall__Outputs(this);
  }
}

export class SetCapCall__Inputs {
  _call: SetCapCall;

  constructor(call: SetCapCall) {
    this._call = call;
  }

  get newCap(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetCapCall__Outputs {
  _call: SetCapCall;

  constructor(call: SetCapCall) {
    this._call = call;
  }
}

export class SetControllerCall extends ethereum.Call {
  get inputs(): SetControllerCall__Inputs {
    return new SetControllerCall__Inputs(this);
  }

  get outputs(): SetControllerCall__Outputs {
    return new SetControllerCall__Outputs(this);
  }
}

export class SetControllerCall__Inputs {
  _call: SetControllerCall;

  constructor(call: SetControllerCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetControllerCall__Outputs {
  _call: SetControllerCall;

  constructor(call: SetControllerCall) {
    this._call = call;
  }
}

export class SetManageFeeCall extends ethereum.Call {
  get inputs(): SetManageFeeCall__Inputs {
    return new SetManageFeeCall__Inputs(this);
  }

  get outputs(): SetManageFeeCall__Outputs {
    return new SetManageFeeCall__Outputs(this);
  }
}

export class SetManageFeeCall__Inputs {
  _call: SetManageFeeCall;

  constructor(call: SetManageFeeCall) {
    this._call = call;
  }

  get _manageFee(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetManageFeeCall__Outputs {
  _call: SetManageFeeCall;

  constructor(call: SetManageFeeCall) {
    this._call = call;
  }
}

export class TransferCall extends ethereum.Call {
  get inputs(): TransferCall__Inputs {
    return new TransferCall__Inputs(this);
  }

  get outputs(): TransferCall__Outputs {
    return new TransferCall__Outputs(this);
  }
}

export class TransferCall__Inputs {
  _call: TransferCall;

  constructor(call: TransferCall) {
    this._call = call;
  }

  get recipient(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class TransferCall__Outputs {
  _call: TransferCall;

  constructor(call: TransferCall) {
    this._call = call;
  }

  get value0(): boolean {
    return this._call.outputValues[0].value.toBoolean();
  }
}

export class TransferFromCall extends ethereum.Call {
  get inputs(): TransferFromCall__Inputs {
    return new TransferFromCall__Inputs(this);
  }

  get outputs(): TransferFromCall__Outputs {
    return new TransferFromCall__Outputs(this);
  }
}

export class TransferFromCall__Inputs {
  _call: TransferFromCall;

  constructor(call: TransferFromCall) {
    this._call = call;
  }

  get sender(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get recipient(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class TransferFromCall__Outputs {
  _call: TransferFromCall;

  constructor(call: TransferFromCall) {
    this._call = call;
  }

  get value0(): boolean {
    return this._call.outputValues[0].value.toBoolean();
  }
}

export class WhitelistLiquidityProviderCall extends ethereum.Call {
  get inputs(): WhitelistLiquidityProviderCall__Inputs {
    return new WhitelistLiquidityProviderCall__Inputs(this);
  }

  get outputs(): WhitelistLiquidityProviderCall__Outputs {
    return new WhitelistLiquidityProviderCall__Outputs(this);
  }
}

export class WhitelistLiquidityProviderCall__Inputs {
  _call: WhitelistLiquidityProviderCall;

  constructor(call: WhitelistLiquidityProviderCall) {
    this._call = call;
  }

  get provider(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class WhitelistLiquidityProviderCall__Outputs {
  _call: WhitelistLiquidityProviderCall;

  constructor(call: WhitelistLiquidityProviderCall) {
    this._call = call;
  }
}
