// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class LOG_BLABS extends ethereum.Event {
  get params(): LOG_BLABS__Params {
    return new LOG_BLABS__Params(this);
  }
}

export class LOG_BLABS__Params {
  _event: LOG_BLABS;

  constructor(event: LOG_BLABS) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get blabs(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LOG_NEW_POOL extends ethereum.Event {
  get params(): LOG_NEW_POOL__Params {
    return new LOG_NEW_POOL__Params(this);
  }
}

export class LOG_NEW_POOL__Params {
  _event: LOG_NEW_POOL;

  constructor(event: LOG_NEW_POOL) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LOG_ROUTER extends ethereum.Event {
  get params(): LOG_ROUTER__Params {
    return new LOG_ROUTER__Params(this);
  }
}

export class LOG_ROUTER__Params {
  _event: LOG_ROUTER;

  constructor(event: LOG_ROUTER) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get router(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LOG_USDT extends ethereum.Event {
  get params(): LOG_USDT__Params {
    return new LOG_USDT__Params(this);
  }
}

export class LOG_USDT__Params {
  _event: LOG_USDT;

  constructor(event: LOG_USDT) {
    this._event = event;
  }

  get caller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get router(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LOG_VAULT extends ethereum.Event {
  get params(): LOG_VAULT__Params {
    return new LOG_VAULT__Params(this);
  }
}

export class LOG_VAULT__Params {
  _event: LOG_VAULT;

  constructor(event: LOG_VAULT) {
    this._event = event;
  }

  get vault(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get caller(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Factory extends ethereum.SmartContract {
  static bind(address: Address): Factory {
    return new Factory("Factory", address);
  }

  getBLabs(): Address {
    let result = super.call("getBLabs", "getBLabs():(address)", []);

    return result[0].toAddress();
  }

  try_getBLabs(): ethereum.CallResult<Address> {
    let result = super.tryCall("getBLabs", "getBLabs():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getSwapRouter(): Address {
    let result = super.call("getSwapRouter", "getSwapRouter():(address)", []);

    return result[0].toAddress();
  }

  try_getSwapRouter(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getSwapRouter",
      "getSwapRouter():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getUsdtAddr(): Address {
    let result = super.call("getUsdtAddr", "getUsdtAddr():(address)", []);

    return result[0].toAddress();
  }

  try_getUsdtAddr(): ethereum.CallResult<Address> {
    let result = super.tryCall("getUsdtAddr", "getUsdtAddr():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getVault(): Address {
    let result = super.call("getVault", "getVault():(address)", []);

    return result[0].toAddress();
  }

  try_getVault(): ethereum.CallResult<Address> {
    let result = super.tryCall("getVault", "getVault():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  isLiquidityPool(b: Address): boolean {
    let result = super.call(
      "isLiquidityPool",
      "isLiquidityPool(address):(bool)",
      [ethereum.Value.fromAddress(b)],
    );

    return result[0].toBoolean();
  }

  try_isLiquidityPool(b: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "isLiquidityPool",
      "isLiquidityPool(address):(bool)",
      [ethereum.Value.fromAddress(b)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  newLiquidityPool(): Address {
    let result = super.call(
      "newLiquidityPool",
      "newLiquidityPool():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_newLiquidityPool(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "newLiquidityPool",
      "newLiquidityPool():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class CollectCall extends ethereum.Call {
  get inputs(): CollectCall__Inputs {
    return new CollectCall__Inputs(this);
  }

  get outputs(): CollectCall__Outputs {
    return new CollectCall__Outputs(this);
  }
}

export class CollectCall__Inputs {
  _call: CollectCall;

  constructor(call: CollectCall) {
    this._call = call;
  }

  get pool(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class CollectCall__Outputs {
  _call: CollectCall;

  constructor(call: CollectCall) {
    this._call = call;
  }
}

export class NewLiquidityPoolCall extends ethereum.Call {
  get inputs(): NewLiquidityPoolCall__Inputs {
    return new NewLiquidityPoolCall__Inputs(this);
  }

  get outputs(): NewLiquidityPoolCall__Outputs {
    return new NewLiquidityPoolCall__Outputs(this);
  }
}

export class NewLiquidityPoolCall__Inputs {
  _call: NewLiquidityPoolCall;

  constructor(call: NewLiquidityPoolCall) {
    this._call = call;
  }
}

export class NewLiquidityPoolCall__Outputs {
  _call: NewLiquidityPoolCall;

  constructor(call: NewLiquidityPoolCall) {
    this._call = call;
  }

  get value0(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class SetBLabsCall extends ethereum.Call {
  get inputs(): SetBLabsCall__Inputs {
    return new SetBLabsCall__Inputs(this);
  }

  get outputs(): SetBLabsCall__Outputs {
    return new SetBLabsCall__Outputs(this);
  }
}

export class SetBLabsCall__Inputs {
  _call: SetBLabsCall;

  constructor(call: SetBLabsCall) {
    this._call = call;
  }

  get b(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetBLabsCall__Outputs {
  _call: SetBLabsCall;

  constructor(call: SetBLabsCall) {
    this._call = call;
  }
}

export class SetSwapRouterCall extends ethereum.Call {
  get inputs(): SetSwapRouterCall__Inputs {
    return new SetSwapRouterCall__Inputs(this);
  }

  get outputs(): SetSwapRouterCall__Outputs {
    return new SetSwapRouterCall__Outputs(this);
  }
}

export class SetSwapRouterCall__Inputs {
  _call: SetSwapRouterCall;

  constructor(call: SetSwapRouterCall) {
    this._call = call;
  }

  get router(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetSwapRouterCall__Outputs {
  _call: SetSwapRouterCall;

  constructor(call: SetSwapRouterCall) {
    this._call = call;
  }
}

export class SetUsdtAddrCall extends ethereum.Call {
  get inputs(): SetUsdtAddrCall__Inputs {
    return new SetUsdtAddrCall__Inputs(this);
  }

  get outputs(): SetUsdtAddrCall__Outputs {
    return new SetUsdtAddrCall__Outputs(this);
  }
}

export class SetUsdtAddrCall__Inputs {
  _call: SetUsdtAddrCall;

  constructor(call: SetUsdtAddrCall) {
    this._call = call;
  }

  get usdtAddr(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetUsdtAddrCall__Outputs {
  _call: SetUsdtAddrCall;

  constructor(call: SetUsdtAddrCall) {
    this._call = call;
  }
}

export class SetVaultCall extends ethereum.Call {
  get inputs(): SetVaultCall__Inputs {
    return new SetVaultCall__Inputs(this);
  }

  get outputs(): SetVaultCall__Outputs {
    return new SetVaultCall__Outputs(this);
  }
}

export class SetVaultCall__Inputs {
  _call: SetVaultCall;

  constructor(call: SetVaultCall) {
    this._call = call;
  }

  get newVault(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetVaultCall__Outputs {
  _call: SetVaultCall;

  constructor(call: SetVaultCall) {
    this._call = call;
  }
}
