// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class OracleUpdated extends ethereum.Event {
  get params(): OracleUpdated__Params {
    return new OracleUpdated__Params(this);
  }
}

export class OracleUpdated__Params {
  _event: OracleUpdated;

  constructor(event: OracleUpdated) {
    this._event = event;
  }

  get token(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get oracle(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get oracleType(): i32 {
    return this._event.parameters[2].value.toI32();
  }

  get decimals(): i32 {
    return this._event.parameters[3].value.toI32();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class PriceReader__getCompatiblePairPriceE18Result {
  value0: BigInt;
  value1: i32;

  constructor(value0: BigInt, value1: i32) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set(
      "value1",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value1)),
    );
    return map;
  }

  getPriceE18(): BigInt {
    return this.value0;
  }

  getSource(): i32 {
    return this.value1;
  }
}

export class PriceReader__getOracleUsdPriceE18Result {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getPriceE18(): BigInt {
    return this.value0;
  }

  getUpdatedAt(): BigInt {
    return this.value1;
  }
}

export class PriceReader__getUniswapV2PairPriceE18Result {
  value0: BigInt;
  value1: Address;

  constructor(value0: BigInt, value1: Address) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    return map;
  }

  getPriceE18(): BigInt {
    return this.value0;
  }

  getPair(): Address {
    return this.value1;
  }
}

export class PriceReader__getUniswapV2PairPricesE18Result {
  value0: Array<BigInt>;
  value1: Array<Address>;

  constructor(value0: Array<BigInt>, value1: Array<Address>) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigIntArray(this.value0));
    map.set("value1", ethereum.Value.fromAddressArray(this.value1));
    return map;
  }

  getPricesE18(): Array<BigInt> {
    return this.value0;
  }

  getPairs(): Array<Address> {
    return this.value1;
  }
}

export class PriceReader__oracleOfResult {
  value0: Address;
  value1: i32;
  value2: i32;

  constructor(value0: Address, value1: i32, value2: i32) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddress(this.value0));
    map.set(
      "value1",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value1)),
    );
    map.set(
      "value2",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value2)),
    );
    return map;
  }

  getOracle(): Address {
    return this.value0;
  }

  getOracleType(): i32 {
    return this.value1;
  }

  getDecimals(): i32 {
    return this.value2;
  }
}

export class PriceReader extends ethereum.SmartContract {
  static bind(address: Address): PriceReader {
    return new PriceReader("PriceReader", address);
  }

  ORACLE_CHAINLINK_V3(): i32 {
    let result = super.call(
      "ORACLE_CHAINLINK_V3",
      "ORACLE_CHAINLINK_V3():(uint8)",
      [],
    );

    return result[0].toI32();
  }

  try_ORACLE_CHAINLINK_V3(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "ORACLE_CHAINLINK_V3",
      "ORACLE_CHAINLINK_V3():(uint8)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  ORACLE_LATEST_ANSWER(): i32 {
    let result = super.call(
      "ORACLE_LATEST_ANSWER",
      "ORACLE_LATEST_ANSWER():(uint8)",
      [],
    );

    return result[0].toI32();
  }

  try_ORACLE_LATEST_ANSWER(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "ORACLE_LATEST_ANSWER",
      "ORACLE_LATEST_ANSWER():(uint8)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  ORACLE_NONE(): i32 {
    let result = super.call("ORACLE_NONE", "ORACLE_NONE():(uint8)", []);

    return result[0].toI32();
  }

  try_ORACLE_NONE(): ethereum.CallResult<i32> {
    let result = super.tryCall("ORACLE_NONE", "ORACLE_NONE():(uint8)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  getCompatiblePairPriceE18(
    pool: Address,
    baseToken: Address,
    quoteToken: Address,
  ): PriceReader__getCompatiblePairPriceE18Result {
    let result = super.call(
      "getCompatiblePairPriceE18",
      "getCompatiblePairPriceE18(address,address,address):(uint256,uint8)",
      [
        ethereum.Value.fromAddress(pool),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );

    return new PriceReader__getCompatiblePairPriceE18Result(
      result[0].toBigInt(),
      result[1].toI32(),
    );
  }

  try_getCompatiblePairPriceE18(
    pool: Address,
    baseToken: Address,
    quoteToken: Address,
  ): ethereum.CallResult<PriceReader__getCompatiblePairPriceE18Result> {
    let result = super.tryCall(
      "getCompatiblePairPriceE18",
      "getCompatiblePairPriceE18(address,address,address):(uint256,uint8)",
      [
        ethereum.Value.fromAddress(pool),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PriceReader__getCompatiblePairPriceE18Result(
        value[0].toBigInt(),
        value[1].toI32(),
      ),
    );
  }

  getOraclePairPriceE18(baseToken: Address, quoteToken: Address): BigInt {
    let result = super.call(
      "getOraclePairPriceE18",
      "getOraclePairPriceE18(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );

    return result[0].toBigInt();
  }

  try_getOraclePairPriceE18(
    baseToken: Address,
    quoteToken: Address,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getOraclePairPriceE18",
      "getOraclePairPriceE18(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getOracleUsdPriceE18(
    token: Address,
  ): PriceReader__getOracleUsdPriceE18Result {
    let result = super.call(
      "getOracleUsdPriceE18",
      "getOracleUsdPriceE18(address):(uint256,uint256)",
      [ethereum.Value.fromAddress(token)],
    );

    return new PriceReader__getOracleUsdPriceE18Result(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_getOracleUsdPriceE18(
    token: Address,
  ): ethereum.CallResult<PriceReader__getOracleUsdPriceE18Result> {
    let result = super.tryCall(
      "getOracleUsdPriceE18",
      "getOracleUsdPriceE18(address):(uint256,uint256)",
      [ethereum.Value.fromAddress(token)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PriceReader__getOracleUsdPriceE18Result(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  getPoolPairPriceE18(
    pool: Address,
    baseToken: Address,
    quoteToken: Address,
  ): BigInt {
    let result = super.call(
      "getPoolPairPriceE18",
      "getPoolPairPriceE18(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(pool),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );

    return result[0].toBigInt();
  }

  try_getPoolPairPriceE18(
    pool: Address,
    baseToken: Address,
    quoteToken: Address,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getPoolPairPriceE18",
      "getPoolPairPriceE18(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(pool),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getPoolWeightedPairPriceE18(
    pool: Address,
    baseToken: Address,
    quoteToken: Address,
  ): BigInt {
    let result = super.call(
      "getPoolWeightedPairPriceE18",
      "getPoolWeightedPairPriceE18(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(pool),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );

    return result[0].toBigInt();
  }

  try_getPoolWeightedPairPriceE18(
    pool: Address,
    baseToken: Address,
    quoteToken: Address,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getPoolWeightedPairPriceE18",
      "getPoolWeightedPairPriceE18(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(pool),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getUniswapV2PairPriceE18(
    factory: Address,
    baseToken: Address,
    quoteToken: Address,
  ): PriceReader__getUniswapV2PairPriceE18Result {
    let result = super.call(
      "getUniswapV2PairPriceE18",
      "getUniswapV2PairPriceE18(address,address,address):(uint256,address)",
      [
        ethereum.Value.fromAddress(factory),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );

    return new PriceReader__getUniswapV2PairPriceE18Result(
      result[0].toBigInt(),
      result[1].toAddress(),
    );
  }

  try_getUniswapV2PairPriceE18(
    factory: Address,
    baseToken: Address,
    quoteToken: Address,
  ): ethereum.CallResult<PriceReader__getUniswapV2PairPriceE18Result> {
    let result = super.tryCall(
      "getUniswapV2PairPriceE18",
      "getUniswapV2PairPriceE18(address,address,address):(uint256,address)",
      [
        ethereum.Value.fromAddress(factory),
        ethereum.Value.fromAddress(baseToken),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PriceReader__getUniswapV2PairPriceE18Result(
        value[0].toBigInt(),
        value[1].toAddress(),
      ),
    );
  }

  getUniswapV2PairPricesE18(
    factory: Address,
    baseTokens: Array<Address>,
    quoteToken: Address,
  ): PriceReader__getUniswapV2PairPricesE18Result {
    let result = super.call(
      "getUniswapV2PairPricesE18",
      "getUniswapV2PairPricesE18(address,address[],address):(uint256[],address[])",
      [
        ethereum.Value.fromAddress(factory),
        ethereum.Value.fromAddressArray(baseTokens),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );

    return new PriceReader__getUniswapV2PairPricesE18Result(
      result[0].toBigIntArray(),
      result[1].toAddressArray(),
    );
  }

  try_getUniswapV2PairPricesE18(
    factory: Address,
    baseTokens: Array<Address>,
    quoteToken: Address,
  ): ethereum.CallResult<PriceReader__getUniswapV2PairPricesE18Result> {
    let result = super.tryCall(
      "getUniswapV2PairPricesE18",
      "getUniswapV2PairPricesE18(address,address[],address):(uint256[],address[])",
      [
        ethereum.Value.fromAddress(factory),
        ethereum.Value.fromAddressArray(baseTokens),
        ethereum.Value.fromAddress(quoteToken),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PriceReader__getUniswapV2PairPricesE18Result(
        value[0].toBigIntArray(),
        value[1].toAddressArray(),
      ),
    );
  }

  oracleOf(param0: Address): PriceReader__oracleOfResult {
    let result = super.call(
      "oracleOf",
      "oracleOf(address):(address,uint8,uint8)",
      [ethereum.Value.fromAddress(param0)],
    );

    return new PriceReader__oracleOfResult(
      result[0].toAddress(),
      result[1].toI32(),
      result[2].toI32(),
    );
  }

  try_oracleOf(
    param0: Address,
  ): ethereum.CallResult<PriceReader__oracleOfResult> {
    let result = super.tryCall(
      "oracleOf",
      "oracleOf(address):(address,uint8,uint8)",
      [ethereum.Value.fromAddress(param0)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PriceReader__oracleOfResult(
        value[0].toAddress(),
        value[1].toI32(),
        value[2].toI32(),
      ),
    );
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ClearOracleCall extends ethereum.Call {
  get inputs(): ClearOracleCall__Inputs {
    return new ClearOracleCall__Inputs(this);
  }

  get outputs(): ClearOracleCall__Outputs {
    return new ClearOracleCall__Outputs(this);
  }
}

export class ClearOracleCall__Inputs {
  _call: ClearOracleCall;

  constructor(call: ClearOracleCall) {
    this._call = call;
  }

  get token(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ClearOracleCall__Outputs {
  _call: ClearOracleCall;

  constructor(call: ClearOracleCall) {
    this._call = call;
  }
}

export class SetOracleCall extends ethereum.Call {
  get inputs(): SetOracleCall__Inputs {
    return new SetOracleCall__Inputs(this);
  }

  get outputs(): SetOracleCall__Outputs {
    return new SetOracleCall__Outputs(this);
  }
}

export class SetOracleCall__Inputs {
  _call: SetOracleCall;

  constructor(call: SetOracleCall) {
    this._call = call;
  }

  get token(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get oracle(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get oracleType(): i32 {
    return this._call.inputValues[2].value.toI32();
  }

  get oracleDecimals(): i32 {
    return this._call.inputValues[3].value.toI32();
  }
}

export class SetOracleCall__Outputs {
  _call: SetOracleCall;

  constructor(call: SetOracleCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}
